language: node_js
node_js:
  - "lts/*"
git:
  lfs_skip_smudge: true
script:
  - npm run build
# deploy is done with a github action
# deploy:
#   skip-cleanup: true
#   provider: firebase
#   on:
#     branch: master
cache: npm
